### ISSUE TITLE
"Could not parse SVGO configuration" in e2e tests

### ISSUE THREAD

**Issue by ericcornelissen** [ericcornelissen/svgo-action#548]
# Bug Report

- **SVGO Action version**: The v3 development branch ([v3.0.0](https://github.com/ericcornelissen/svgo-action/releases/tag/v3.0.0) appears unaffected)

- **On**: [end-to-end tests](https://github.com/ericcornelissen/svgo-action/blob/f6cde792c043613360a44151b0345f9a21542e4c/.github/workflows/push-checks.yml#L107-L221)

## Description

The end-to-end tests report

```log
[WARNING] Could not parse SVGO configuration
```

for both the [built-in, v2](https://github.com/ericcornelissen/svgo-action/blob/f6cde792c043613360a44151b0345f9a21542e4c/.github/workflows/push-checks.yml#L113-L115) and [project, v2](https://github.com/ericcornelissen/svgo-action/blob/f6cde792c043613360a44151b0345f9a21542e4c/.github/workflows/push-checks.yml#L120-L123) end-to-end test scenarios.

![v3.0.0 development branch e2e tests annotations preview](https://user-images.githubusercontent.com/3742559/166834898-6de56d59-c017-472f-b904-6a495b3d16a5.png)

The fact that there's no warning for the [project, v1](https://github.com/ericcornelissen/svgo-action/blob/f6cde792c043613360a44151b0345f9a21542e4c/.github/workflows/push-checks.yml#L116-L119) scenario suggests this is related to parsing JavaScript configuration files.

An initial idea is that it's related to switch from the `node-eval` dependency to `eval` (#536). This theory is supported by the fact that for [the commit of the v3 release](https://github.com/ericcornelissen/svgo-action/commit/bd12b9be17ea5d7e76a460e866e4fe743a6f4119) the [end-to-end tests](https://github.com/ericcornelissen/svgo-action/actions/runs/2073273252) do not yet indicate a problem (at least at the time).

![v3.0.0 (tag) e2e tests annotations preview](https://user-images.githubusercontent.com/3742559/166835671-8bb55967-a19e-484b-ab3c-46d4d2d912c4.png)

### Is v2 affected?

A quick look at the [e2e tests annotations](https://github.com/ericcornelissen/svgo-action/actions/runs/2223238235) for [2.1.6](https://github.com/ericcornelissen/svgo-action/releases/tag/v2.1.6) suggests this is a v3 exclusive problem, as there are no warnings related to config parsing.

![v2.1.6 e2e tests annotations preview](https://user-images.githubusercontent.com/3742559/166834864-84e8a1be-0008-4acc-ad8e-77fad7215f3d.png)

### Actual Behaviour

A parsing error for JavaScript configuration files (both when using built-in SVGO v2 **and** project SVGO v2) is reported.

It is not yet confirmed whether the configuration file is actually not being parsed, and hence ignored when running SVGO.

### Expected Behaviour

There's no parsing warning when the Action needs to use a valid JavaScript configuration file for SVGO.

## Working Example

Run the e2e tests in the CI for commit c2afd54aa1d507a3da8da7a054e9536a7cfd9292.

**Comment by ericcornelissen** [comment]
I was able to confirm the problem, as well as confirm that [v3.0.0](https://github.com/ericcornelissen/svgo-action/releases/tag/v3.0.0) is unaffected (hence the removed [the `bug` label](https://github.com/ericcornelissen/svgo-action/labels/bug)).

Specifically, the problem is that [the eval package](https://www.npmjs.com/package/eval) contains a line of code that appears incompatible with modern JavaScript resulting in an error before JavaScript configuration files are being parsed. Specifically, the following error is thrown for certain inputs:

```log
.../svgo-action/node_modules/eval/eval.js:38
  var _filename = filename || module.parent.filename;
                                            ^

TypeError: Cannot read properties of undefined (reading 'filename')
    at module.exports (.../svgo-action/node_modules/eval/eval.js:38:45)
    at file:.../svgo-action/test.js:3:1
    at ModuleJob.run (node:internal/modules/esm/module_job:198:25)
    at async Promise.all (index 0)
    at async ESMLoader.import (node:internal/modules/esm/loader:385:24)
    at async loadESM (node:internal/process/esm_loader:88:5)
    at async handleMainPromise (node:internal/modules/run_main:61:12)
```

<details>
<summary>View the test.js script</summary>

```js
import jsEval from "eval";

jsEval("module.exports = { };");
```

</details>

Specifically, if no `filename` (second argument) is provided when using eval, this error happen - leading to the "[WARNING] Could not parse SVGO configuration" seen from this Action.
